### ISSUE TITLE
Confusing behavior on setindex! of a vector Observable

### ISSUE THREAD

**Issue by vilim** [JuliaGizmos/Observables.jl#31] opened 2018-12-03 22:47 UTC
I find the following behavior a bit confusing (from [Makie examples](http://makie.juliaplots.org/stable/examples-interaction.html#Edit-Polygon-1)):
```
points = Observable(Point2f0[(0, 0), (0.5, 0.5), (1.0, 0.0)]) # AbstractPlotting renames Observables to Nodes it seems
```
later, in a function
```
          points[][idx[]] = pos
          points[] = points[]
```
The example does not work if the last line is excluded, even though it seems to be doing nothing. Is the issue that `points[][idx[]] = pos` somehow does not send a change signal?

**Comment by mschauer** [comment] 2019-04-24 15:12
My take: `points[] = ...` calls `setindex!` on an observable, triggering a signal.
`points[][1] = ...` calls `getindex` on an observable (and `setindex!`es the result), not triggering a signal.

**Comment by vilim** [comment] 2019-04-25 21:05
Ah, that makes sense, thanks! Maybe there could be a more intuitive method of triggering the signal, somehting like trigger(points), that executes the rest of the setindex[] method, without the first line? Or just as an alias for that line? Performance-wise, I guess o.val = val is anyway compiled to a no-op.

**Comment by goretkin** [comment] 2020-03-14 20:42
Probably more semantically obvious than `points[] = points[]` is to do `Observables.notify!(points)`.

**Comment by travigd** [comment] 2020-03-23 21:40
I'm going to close this as intended behavior.

It might make sense to warn more about using mutable values inside of observables in the documentation.

**Closed by travigd** 2020-03-23 21:40 UTC
