### ISSUE TITLE
Add `async_latest` to the online docs

### ISSUE THREAD

**Issue by Datseris** [JuliaGizmos/Observables.jl#43] opened 2020-04-16 09:09 UTC
Very useful function :)

**Comment by cserteGT3** [comment] 2020-06-22 09:33
It should be part of the documentation, the problem is, that the latest commit on the `gh-pages` branch is from 2018, so no documentation haven been deployed since.

There are some details in #41

**Comment by timholy** [comment] 2021-02-22 10:25
This is fixed in the `dev` documentation, which will hopefully soon become `stable`.

**Closed by timholy** 2021-02-22 10:25 UTC
Labels: docs, enhancement, help wanted
